spring.application.name=sb-ecome-backend

spring.h2.console.enabled = true
spring.datasource.url = jdbc:h2:mem:test

project.image=images/

#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.hibernate.ddl-auto=update

spring.app.jwtSecret=mySecretKey123912738jkhjghguhguyfyfyghvyuhgyuhgbyuguftrdfgh
spring.app.jwtExpirationMs=300000

logging.level.org.springframework=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.com.example.securitydemo=DEBUG